### ISSUE TITLE
Munkireport Python3?

### ISSUE THREAD

**Issue by jelockwood** [autopkg/davidbpirie-recipes#2]
Hi @davidbpirie 

I see you have written AutoPkg recipes for both Python2 and Python3 supposedly downloading from the munkireport/MunkiReport-Python repo.

There is indeed a Python2 available via that repo for use with MunkiReport but I cannot see a Python3 in that repo. I am presuming the MunkiReport author has removed it as MunkiReport sadly still uses only Python2.

I was wondering if you could confirm this?

I was contemplating using this as a way to install a copy of Python3 for other uses.

**Comment by davidbpirie** [comment]
@jelockwood if you haven't already found a solution, I would suggest looking at https://github.com/gregneagle/relocatable-python.
