### ISSUE TITLE
Cisco Secure Client preinstall script doesn't execute after repackaging

### ISSUE THREAD

**Issue by lhetke** [autopkg/davidbpirie-recipes#4]
We encountered a Problem while testing the following recipe:

CiscoSecureClient/CiscoSecureClient.pkg.recipe.yaml

With the 5.0.00556 version of the Cisco Secure Client installer the preinstall script within the Cisco Secure Client.pkg does not execute properly after the packaging done by the recipe. This results in the previous Cisco Secure Client installation not being uninstalled.

We added another FileCreator processor to the recipe to solve this problem:

```
  - Processor: FileCreator
    Arguments:
      file_content: |
        #!/bin/zsh
        # Eric Hoch

        # Quick and dirty remove the old Cisco Secure Client

        if [ -f /opt/cisco/secureclient/bin/cisco_secure_client_uninstall.sh ]; then
        /opt/cisco/secureclient/bin/cisco_secure_client_uninstall.sh
        exit 0
        fi
      file_mode: "0755"
      file_path: "%RECIPE_CACHE_DIR%/%NAME%/scripts/preinstall"
```
I hope this helps or maybe there is another solution to the problem?

**Comment by davidbpirie** [comment]
@lhetke thanks for the feedback. I have incorporated this into the recipe.
