### ISSUE TITLE
Azul Zulu 17 JRE download query

### ISSUE THREAD

**Issue by jelockwood** [autopkg/davidbpirie-recipes#5]
@davidbpirie 
You may remember last year we worked together on some issues I had creating AutoPkg Munki recipes to download via your matching download recipe. This was at the time purely in relation to downloading JDK versions and we solved all those issues and this is still working fine currently for JDK releases.

Today I decided I would like to have a JRE version 17 and I therefore used exactly the same approach to make a new AutoPkg Munki recipe and fill in details instead to download the JRE instead of a JDK.

This is pretty much working but I have hit one minor issue which I think is related to your download recipe _and how Azul have listed versions_.

Currently they have one JRE 17 for Apple Silicon, but _two_ JRE 17 for Intel listed. See screen capture below. Your recipe is downloading unfortunately the older of the two Intel versions and ignoring the newer one. Ideally you would alter this.

![Screenshot 2023-05-18 at 12 12 14](https://github.com/autopkg/davidbpirie-recipes/assets/4300786/d6a348a1-3ae2-4908-b2f8-d18368cfa48e)

**Comment by davidbpirie** [comment]
@jelockwood can you please provide all the input variable values you are using? ie `JAVA_MAJOR_VERSION`, `ARCHITECTURE`, `DOWNLOAD_FILE_EXTENSION`, `BUNDLE_TYPE`?

**Comment by davidbpirie** [comment]
I suspect the issue is to do with `DOWNLOAD_FILE_EXTENSION` - if you hover over the Download buttons, you will see that for x86 17.0.7+7 only offers `.zip` and `.tar.gz`, and 17+35 only offers `.dmg`; whereas ARM has all three extensions available for 17.0.7+7.

**Comment by davidbpirie** [comment]
My munki recipe relies on my pkg recipe, which is written expecting to use my download recipe with `DOWNLOAD_FILE_EXTENSION` set to dmg, as it will then extract a pkg file from that dmg. If the source version combination you are after doesn't include a dmg, then you will need to write your own recipe that creates a pkg from one of the other file types published.

**Comment by jelockwood** [comment]
Ah!
When I first looked this and reported it, I merely saw that it was listing two versions of the JRE17 for x86 processors and that only the older one was being downloaded.

I therefore assumed that your recipe had been confused by this and picked the last one listed which happened to be the older one. However prompted by your reply I have gone back and looked again and yes you are right. I am 'asking' for a DMG and _only_ the older one listed is available for x86 in the form of a DMG, the newer one is only available as a zip or tar.gz and not DMG.

So it would seem to be down to Azul making a mess of things.

I am therefore happy for you to close this issue.
