### ISSUE TITLE
SketchUpPro - URLDownloader: Error: curl: (22) The requested URL returned error: 403

### ISSUE THREAD

**Issue by Stette** [autopkg/davidbpirie-recipes#6]
Autopkg fails to download the newest installer from Trimble.

The redirect doesn't seem to work. If I go to the same URL with a web browser I get redirected and the download starts, cut CURL fails to download the .dmg.

I see that other recipes for SketchUp uses `request_headers`, like:

```
<key>Processor</key>
            <string>URLDownloader</string>
            <key>Arguments</key>
            <dict>
                <key>filename</key>
                <string>%NAME%.dmg</string>
                <key>url</key>
                <string>https://www.sketchup.com/sketchup/2023/SketchUpPro-dmg</string>
                <key>request_headers</key>
                <dict>
                    <key>user-agent</key>
                    <string>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15</string>
```

Can this maybe fix it?

On our override we have also hard coded the` RELEASE_YEAR` but maybe some fancy logic could update this as well?

**Comment by Stette** [comment]
I see the download recipe has now been updated. Guessing this will fix the issue 👍🏼

**Comment by Stette** [comment]
It did! Thanks @davidbpirie

**Comment by davidbpirie** [comment]
Hi @Stette, apologies for not confirming sooner. Yes I implemented the change, and in my testing it initially resolved the issue, but on later re-runs of the recipe I was getting errors again, and I didn't have the time to dig deeper.

Can you confirm this is still working OK for you? It might have just been an issue on my test device.

**Comment by Stette** [comment]
Hi David! Yeah, I had the same issue actually. It worked the first day after the fix, but the following day it broke again. We thought maybe we had a local error.

**Comment by davidbpirie** [comment]
Looks like we aren't the only ones seeing an issue:
https://github.com/autopkg/dataJAR-recipes/issues/304
