### ISSUE TITLE
Azul website currently missing some Intel builds

### ISSUE THREAD

**Issue by jelockwood** [autopkg/davidbpirie-recipes#7]
@davidbpirie 

This is not a fault of your AzulZulu recipe but I thought I would raise this issue to alert you (and others) to the current problem.

See - https://github.com/jelockwood/recipes/issues/2 

I raised this against my corresponding Munki recipe(s) for AzulZulu which use your Download recipe. I use my own Munki recipe(s) because I use plist format to make them compatible with AutoPkgr which does not support YAML recipes.

I have submitted a ticket regarding this to Azul.

**Comment by davidbpirie** [comment]
@jelockwood there is no reason for you to have your own copy of the recipe just to use plist format - a simple override (which is basically a recipe with no Processor steps) using mine as a parent would also work.

As you have probably figured out, this isn't an issue with the recipe, but rather the availability of certain combinations of builds from Azul.
