### ISSUE TITLE
wrong version of Logitech Options Plus

### ISSUE THREAD

**Issue by user1233445** [autopkg/davidbpirie-recipes#8]
Hi,

while packaging Logi Options+ using your recipe, I noticed a discrepancy with the package version and the current version of the application. It appears that the app installer has the version 1.76.0.583666, while the installed app version is 1.76.583666.

App Version:
![image](https://github.com/user-attachments/assets/18624b7f-93a7-4c89-a437-1a0ee1ae6f34)

Package Version:
![image](https://github.com/user-attachments/assets/af6f9133-132d-4f82-9d01-3fbc0a3515ae)

Could you please adjust the recipe to align with the installed version of the application? 

Thank you in advance!

Best

**Comment by davidbpirie** [comment]
The LogitechOptionsPlus.download.recipe.yaml recipe uses the Logitech Options+ Offline Installer as its source, which unfortunately Logitech does not update with every available version. At one point I raised a support case with them to see if they could improve their process, but it was unsuccessful.
If you find another way of downloading the source package, please let me know.

**Comment by davidbpirie** [comment]
Thanks for picking up on this. The issue is that the recipe uses the offline installer, which is a standalone app, and the recipe is extracting the version from the installer rather than the app itself. I have modified the download recipe to only use the 1st, 2nd, and last segments of the installer version (ie strip out the extra .0).

**Comment by user1233445** [comment]
It seems Logitech has once again changed the versioning behavior. Could you kindly review your recipe? I truly appreciate your efforts and thank you in advance!

```
Versioner: No value supplied for skip_single_root_dir, setting default value of: False
Versioner: Found version 1.83.635658 in file /Users/.../expand/logioptionsplus_installer_offline.app/Contents/Info.plist
{'Output': {'version': '1.83.635658'}}
com.github.jazzace.processors/TextSearcher
{'Input': {'re_pattern': '^[0-9]\\.[0-9]*',
           'result_output_var_name': 'version_prefix',
           'text_in': '1.83.635658'}}
TextSearcher: Found matching text (version_prefix): 1.83
{'Output': {'version_prefix': '1.83'}}
com.github.jazzace.processors/TextSearcher
{'Input': {'re_pattern': '^[0-9]\\.[0-9]*\\.[0-9]\\.(.*)',
           'result_output_var_name': 'version_suffix',
           'text_in': '1.83.635658'}}
No match found in passed text: 1.83.635658
Failed.

The following recipes failed:
    local.prov.jamf.LogitechOptionsPlus
        Error in local.prov.jamf.LogitechOptionsPlus: Processor: com.github.jazzace.processors/TextSearcher: Error: No match found in passed text: 1.83.635658

```

**Comment by davidbpirie** [comment]
Thanks for letting me know. Looks like Logitech have brought the version scheme for the offline installer app in line with the deployed app, so I no longer need to actively remove the extra segment. I have removed the extra processors now.
